### PR TITLE
Remove body from content_panels on LocationPage

### LINKED ISSUE #111: Remove page body field from content_panels on Locations
We're getting by fine with short introduction and a map  and not using body in the demo. Remove?

### PR DESCRIPTION
**Pull request by shacker**
Resolves #111

### CODE REVIEW

**Comment by heymonkeyriot** [comment]
I've started adding in body copy to these pages as they feel quite stubby. There's a couple of them that also feel like the introductory on some of them are slightly too long. I think we should retain the body text here.

**Comment by shacker** [comment]
I personally feel the location pages don't need much info - short and sweet - just the location, m'aam. But I'll defer to you on this one. We can kill the PR.

**Comment by heymonkeyriot** [comment]
Oh, you've merged the PR. It's a little odd with the design as there's a lot of things in a relatively small amount of space. I personally think we should reinstate.

**Comment by shacker** [comment]
I merged it with a 2nd commit which reverted the first change and added target = _blank.

**Comment by shacker** [comment]
Oh, sorry, I was referring to #113 above. Yeah this merge looks like a mistake, sorry. Will reinstate the field tonight.

**Comment by shacker** [comment]
Body field on LocationPage is restored in latest PR.

**Pull request merged**
