### PR TITLE
Remove  aboutlocations

### LINKED ISSUE #54: Handle locations on About template, or ditch that relationship
Locations are shown as children of `LocationIndex`. About also has `AboutLocationRelationship`, which lets you manually attach those same locations to the about page. But if you do, they don't show up since the template doesn't handle them. 

Either add that handling to the about template, or remove the `AboutLocationRelationship` since it duplicates data on Locations and we're going to use About for info about  the demo itself anyway.

### PR DESCRIPTION
**Pull request by shacker**
- Overlaps with functionality of Locations view
- Resolves #54

### CODE REVIEW

**Comment by daaray** [comment]
👍

**Comment by heymonkeyriot** [comment]
Looks good testing here.

**Comment by daaray** [comment]
oops I flew in under the radar. Sorry @heymonkeyriot.

**Comment by heymonkeyriot** [comment]
No worries at all :) It's always good to have two pairs on eyes

**Pull request merged**
