### PR TITLE
Styling form page

### PR DESCRIPTION
**Pull request by heymonkeyriot**
**Ready for review** see [comment below](https://github.com/wagtail/bakerydemo/pull/73#issuecomment-282970038) for more details

c/f #15 for original issue

 - [x] Use `{% for field in form %}` rather than `{{ form.as_p }}` in template
 - [x] Style form detail page
 - [x] Style form "thank you" page
 - [x] Fix merge conflicts
 - [x] Understand why date field and datetime field are rendering as type=text
 - [ ] Creating template override for date field and datetime field as per comment from @daaray

### CODE REVIEW

**Comment by heymonkeyriot** [comment]
@daaray and @shacker, if you have the time or inclination to have a look at what might be causing the date field and datetime field to render with a form input `type=text` that'd be awesome. It looks very much as though it's an issue with the AbstractFormField, though having had a quick look at [forms.py](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/forms.py) and [models.py](https://github.com/wagtail/wagtail/blob/master/wagtail/wagtailforms/models.py) of the forms app in Wagtail I can't see any obvious reason why these fields would fail to be correctly cast.

It's simple to replicate the issue, just add either a date field or datetime field to the page and see that it renders as the incorrect field type.

**Comment by daaray** [comment]
@heymonkeyriot we'll have to override the templates, I believe: https://github.com/wagtail/wagtail/issues/1016

**Comment by heymonkeyriot** [comment]
Thanks @daaray. Having done a very limited amount of digging I wonder whether it might be better to do the overriding work as a separate PR/ issue. I think the PR, taking it at it's strictest definition of being about styling the form page, is complete, and think it might be worth merging in. What do you @shacker or @ArnarTumi think?

**Comment by daaray** [comment]
I agree that it should be dealt with as a separate issue.

**Comment by shacker** [comment]
Since we don't have a date/time field on the contact form, that issue doesn't really affect us (or do we need one? Purpose/intent?). 

I personally would rather see wider fields on the desktop view, but that can be solved separately. 

Thanks!

**Comment by shacker** [comment]
We seem to have gotten into a migration quandary, with two `base.0013` files. I did a migration merge which references files

```
    dependencies = [
        ('base', '0013_auto_20170227_2216'),
        ('base', '0013_auto_20170228_0714'),
    ]
```

but I only have 0013_auto_20170228_0714, not the other. Did it get checked in?

**Comment by heymonkeyriot** [comment]
Yup commit  [600bfc4 ](https://github.com/wagtail/bakerydemo/pull/73/commits/600bfc482df833db9dc18fc48d76290f8657b72d0) on this branch pushed up `0013_auto_20170227_2216.py`. I can see it on the [master tree too](https://github.com/wagtail/bakerydemo/tree/master/bakerydemo/base/migrations)

It seems the conflict has come from the removal of the location relationship on the other branch.

**Comment by shacker** [comment]
Huh - not sure what happened there, but all resolved now. I didn't have the latest somehow, and tried to create the missing merge migration, which failed... Reset just now, started over, got it all resolved and pushed the missing migration merge. Sorry for the noise.

**Pull request merged**
