### PR TITLE
Breadcrumb changes

### PR DESCRIPTION
**Pull request by heymonkeyriot**
In the sprint I rather hastily created base to be

```
    <content>
        {% block content-header %}
        {% endblock content-header %}

        {% block breadcrumbs %}
            {% breadcrumbs %}
            {# breadcrumbs is defined in base/templatetags/navigation_tags.py #}
        {% endblock breadcrumbs %}

        {% block content-body %}
        {% endblock content-body %}
    </content>
```

This allowed breadcrumbs to be nested between the hero image of the design and the main content, but having started properly with the styling it's a brittle solution that's going to be a headache.

I'm moving it back to the more orthodox

```
{% block breadcrumbs %}
    {% breadcrumbs %}
    {# breadcrumbs is defined in base/templatetags/navigation_tags.py #}
{% endblock breadcrumbs %}

<content>
    {% block content %}
        
    {% endblock content %}
</content>
```

To do
 - [x] Amending relevant template files
 - [x] Styling breadcrumb
 - [x] Dealing with any merge issues

### CODE REVIEW

**Comment by shacker** [comment]
When I run this branch, all content disappears on the site. Changing the main block from `block content` to `block content-body` brings it back, but thumbnail images on locations index go all stretchy. Can you test?

**Comment by heymonkeyriot** [comment]
Sorry, I should have made it clearer that this branch isn't ready to test yet. I just wanted to create some visibility of the fact it was being done :)

**Comment by shacker** [comment]
Ah - our work team convention is to put a big DO NOT MERGE flag as top comment on WIP branches that also have PRs.

**Comment by heymonkeyriot** [comment]
It's ours too. Sorry, entirely my fault for having done this whilst being rushed out the door by an irate partner who didn't want me working on a Saturday :D

So, I think this is now ready to review. The breadcrumbs should look like
capture d ecran 2017-02-19 a 21 49 03
capture d ecran 2017-02-19 a 21 52 27

(The two images above are with the HTML cherry-picked from branch `51-location-styling-missing-styles` because it's otherwise not possible to show the hero image)

I've used a bit of a hack within the CSS `.breadcrumb-container + content > .hero` to allow the breadcrumb to sit visually above hero images using a negative top-margin, but on pages where there isn't a hero image the breadcrumb will sit above the white background.

There's going to be a lot of conflicts between this and #53 . I would suggest that we merge #53 to master (if no more work required on that PR), then I merge that version of master in to this branch, and resolve the conflicts. Does that sound okay?

**Comment by shacker** [comment]
LOL, I sure get that about partner not loving this weekend work :)

PR #53 is now merged, so rebase away. This looks really polished -  Thanks for all your work on this.

**Comment by shacker** [comment]
LGTM. 

+1 on returning to standard `block content`.

**Comment by heymonkeyriot** [comment]
Awesome. Have rebased. @shacker or @daaray if one of you could double check and merge that'd be awesome.

**Comment by daaray** [comment]
👍 :shipit:

**Pull request merged**
