### PR TITLE
Add icons to registered settings

### PR DESCRIPTION
**Pull request by rohitsrma**
This PR is to validate the changes made in [#11818](https://github.com/wagtail/wagtail/pull/11818).

### Before

image

### After

image

### CODE REVIEW

**Comment by rohitsrma** [comment]
Hello @lb-, Please let me know if any updates are needed here.

**Comment by lb-** [comment]
Thanks @rohitsrma - change looks good but just needs a linting fix. Check the VI report for details.

**Comment by rohitsrma** [comment]
Thanks @lb- I've made the changes.

**Comment by lb-** [comment]
Thanks. Will be a helpful addition to support Manual testing

**Pull request merged**
