### PR TITLE
An idempotent provisioning bakery

### PR DESCRIPTION
**Pull request by shurph**
It's a next one part of [a story about an idempotent provisioning](https://github.com/wagtail/vagrant-wagtail-develop/pull/16) for a developers' env.

### CODE REVIEW

**Comment by shurph** [comment]
Hi @jjanssen I've updated this PR with a new vision of how idempotent provisioning might be realized. Here is a more simple approach.

Could you please review it and, if it's appropriate, merge it?

**Comment by shurph** [comment]
Hi @gasman  I've updated this PR with a new vision of how idempotent provisioning might be realized. Here is a more simple approach.

Could you please review it and, if it's appropriate, merge it?

**Comment by shurph** [comment]
Hi @gasman , could you please provide any update regarding this PR?

**Comment by gasman** [comment]
All looks good to me, thanks @shurph!

**Pull request merged**
