### PR TITLE
Updated uses of StreamField to use JSONField

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
I have edited the stream fields of Bakery demo to work on Wagtail 3.0 as suggested by @cnk in https://wagtailcms.slack.com/archives/C81FGJR2S/p1650812809244809?thread_ts=1650802381.876709&cid=C81FGJR2S.

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @PaarthAgarwal! I've now merged this as a new `wagtail-3.0` branch. The `use_json_field` change in Wagtail creates a problem for bakerydemo, since at the current moment it's not possible to write a StreamField definition that works on the latest released version (2.16) and current main (4.0a0, which drops the backwards compatibility for missing `use_json_field`) - for that reason, I'll also revert the change on main so that the backwards compatibility remains until Wagtail 5.0.

**Comment by PaarthAgarwal** [comment]
> Thanks @PaarthAgarwal! I've now merged this as a new `wagtail-3.0` branch. The `use_json_field` change in Wagtail creates a problem for bakerydemo, since at the current moment it's not possible to write a StreamField definition that works on the latest released version (2.16) and current main (4.0a0, which drops the backwards compatibility for missing `use_json_field`) - for that reason, I'll also revert the change on main so that the backwards compatibility remains until Wagtail 5.0.

Awesome!

**Comment by PaarthAgarwal** [comment]
@gasman, should the readme be updated to point the new users to the wagtail-3.0 branch?

**Comment by gasman** [comment]
No, because once I make the change described above, the bakerydemo master branch will work with Wagtail main again (just with a deprecation warning), so ordinary users won't need to deal with the new branch.

**Comment by PaarthAgarwal** [comment]
Got it👍🏼

**Pull request closed without merging**
