### PR TITLE
Update docker to current/supported tool versions

### PR DESCRIPTION
**Pull request by Pomax**
Closes https://github.com/wagtail/bakerydemo/issues/319

### Docker image updates:

- update postgres to 14.1
- update redis to 6.2

### Django 4.x requirements:

- update python to 3.9
- update django-redis to 5.2.0

### CODE REVIEW

**Comment by Pomax** [comment]
Looks like this has some db issues: the docker build itself works, but initial data load does not:

```
Postgres is up - continuing
/venv/lib/python3.9/site-packages/dotenv.py:56: UserWarning: Not reading /code/.env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
Copying media files to configured storage...
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "wagtailcore_site" does not exist
LINE 1: SELECT (1) AS "a" FROM "wagtailcore_site" WHERE "wagtailcore...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/code/bakerydemo/base/management/commands/load_initial_data.py", line 36, in handle
    if Site.objects.filter(hostname='localhost').exists():
  File "/venv/lib/python3.9/site-packages/django/db/models/query.py", line 815, in exists
    return self.query.has_results(using=self.db)
  File "/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 549, in has_results
    return compiler.has_results()
  File "/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1172, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1202, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: SELECT (1) AS "a" FROM "wagtailcore_site" WHERE "wagtailcore...
                               ^
```

**Comment by gasman** [comment]
@Pomax Just wondering, do you get the same result when trying my WIP branch from https://github.com/wagtail/bakerydemo/issues/319#issuecomment-1033103871? It doesn't look like I'm doing anything substantially different to you, but I don't recall running into anything like this.

Maybe this is a variant of the problem seen on https://github.com/wagtail/docker-wagtail-develop/issues/23, where different containers complete their setup at unpredictable times, and as a result it tries to run migrations / load_initial_data before the database is ready?

**Comment by Pomax** [comment]
Good question: I'll give your branch a try in the morning.

**Comment by Pomax** [comment]
The one big difference is you're pulling 3.10 slim rather than 3.9 slim (I used 3.9 mostly because 3.10 changed a bunch of built-ins and I wanted to err on the side of caution in updating python). When I try to run https://github.com/gasman/bakerydemo/commit/9b62f421bbd70774124ee0bce223fd707e651299 through `docker-compose up --build -d` (after running a `docker system prune --all` just to be absolutely sure it's going to be a clean build) I get the following errors that seem python version related:

```
#8 36.13 Collecting pyasn1<0.5.0,>=0.4.6
#8 36.15   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
#8 36.15      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 120.5 MB/s eta 0:00:00
#8 36.36 Using legacy 'setup.py install' for dj-database-url, since package 'wheel' is not installed.
#8 36.36 Using legacy 'setup.py install' for aws-requests-auth, since package 'wheel' is not installed.
#8 36.37 Using legacy 'setup.py install' for uwsgi, since package 'wheel' is not installed.
#8 36.37 Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
#8 36.71 Installing collected packages: xlwt, Willow, webencodings, uwsgi, pytz, pyasn1, draftjs-exporter, django-dotenv, django_cache_url, dj-database-url, certifi, xlsxwriter, xlrd, wrapt, whitenoise, urllib3, telepath, tablib, sqlparse, soupsieve, six, rsa, pyparsing, pyasn1-modules, psycopg2, protobuf, Pillow, jmespath, idna, et-xmlfile, docutils, django-modelcluster, charset-normalizer, cachetools, asgiref, anyascii, requests, python-dateutil, packaging, openpyxl, l18n, html5lib, googleapis-common-protos, google-resumable-media, google-auth, elasticsearch, Django, deprecated, beautifulsoup4, redis, google-api-core, djangorestframework, django-treebeard, django-taggit, django-storages, django-filter, django-debug-toolbar, botocore, aws-requests-auth, wagtail, s3transfer, google-cloud-core, django-redis, wagtailfontawesome, google-cloud-storage, boto3
#8 36.83   Running setup.py install for uwsgi: started
#8 39.76   Running setup.py install for uwsgi: finished with status 'error'
#8 39.77   error: subprocess-exited-with-error
#8 39.77
#8 39.77   × Running setup.py install for uwsgi did not run successfully.
#8 39.77   │ exit code: 1
#8 39.77   ╰─> [76 lines of output]
#8 39.77       /usr/local/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
#8 39.77         warnings.warn(msg)
#8 39.77       running install
#8 39.77       using profile: buildconf/default.ini
#8 39.77       detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/10/include', '/usr/local/include', '/usr/include/x86_64-linux-gnu', '/usr/include']
#8 39.77       Patching "bin_name" to properly install_scripts dir
#8 39.77       detected CPU cores: 8
#8 39.77       configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_VERSION="\"2.0.20\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="20" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_XML -DUWSGI_XML_EXPAT -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
#8 39.77       *** uWSGI compiling server core ***
#8 39.77       [thread 0][gcc -pthread] core/utils.o
#8 39.77       [thread 2][gcc -pthread] core/protocol.o
#8 39.77       [thread 4][gcc -pthread] core/socket.o
#8 39.77       [thread 3][gcc -pthread] core/logging.o
#8 39.77       [thread 6][gcc -pthread] core/master.o
#8 39.77       [thread 7][gcc -pthread] core/master_utils.o
#8 39.77       [thread 1][gcc -pthread] core/emperor.o
#8 39.77       [thread 5][gcc -pthread] core/notify.o
#8 39.77       [thread 5][gcc -pthread] core/mule.o
#8 39.77       [thread 2][gcc -pthread] core/subscription.o
#8 39.77       [thread 5][gcc -pthread] core/stats.o
#8 39.77       [thread 6][gcc -pthread] core/sendfile.o
#8 39.77       [thread 7][gcc -pthread] core/async.o
#8 39.77       [thread 6][gcc -pthread] core/master_checks.o
#8 39.77       [thread 3][gcc -pthread] core/fifo.o
#8 39.77       [thread 4][gcc -pthread] core/offload.o
#8 39.77       [thread 2][gcc -pthread] core/io.o
#8 39.77       [thread 5][gcc -pthread] core/static.o
#8 39.77       [thread 1][gcc -pthread] core/websockets.o
#8 39.77       [thread 3][gcc -pthread] core/spooler.o
#8 39.77       [thread 7][gcc -pthread] core/snmp.o
#8 39.77       [thread 6][gcc -pthread] core/exceptions.o
#8 39.77       [thread 4][gcc -pthread] core/config.o
#8 39.77       [thread 7][gcc -pthread] core/setup_utils.o
#8 39.77       [thread 1][gcc -pthread] core/clock.o
#8 39.77       [thread 5][gcc -pthread] core/init.o
#8 39.77       [thread 3][gcc -pthread] core/buffer.o
#8 39.77       [thread 6][gcc -pthread] core/reader.o
#8 39.77       [thread 1][gcc -pthread] core/writer.o
#8 39.77       [thread 7][gcc -pthread] core/alarm.o
#8 39.77       [thread 2][gcc -pthread] core/cron.o
#8 39.77       [thread 5][gcc -pthread] core/hooks.o
#8 39.77       [thread 0][gcc -pthread] core/plugins.o
#8 39.77       [thread 4][gcc -pthread] core/lock.o
#8 39.77       [thread 3][gcc -pthread] core/cache.o
#8 39.77       [thread 6][gcc -pthread] core/daemons.o
#8 39.77       [thread 2][gcc -pthread] core/errors.o
#8 39.77       [thread 7][gcc -pthread] core/hash.o
#8 39.77       [thread 1][gcc -pthread] core/master_events.o
#8 39.77       [thread 0][gcc -pthread] core/chunked.o
#8 39.77       [thread 7][gcc -pthread] core/queue.o
#8 39.77       [thread 4][gcc -pthread] core/event.o
#8 39.77       [thread 2][gcc -pthread] core/signal.o
#8 39.77       [thread 5][gcc -pthread] core/strings.o
#8 39.77       [thread 6][gcc -pthread] core/progress.o
#8 39.77       [thread 1][gcc -pthread] core/timebomb.o
#8 39.77       [thread 0][gcc -pthread] core/ini.o
#8 39.77       [thread 7][gcc -pthread] core/fsmon.o
#8 39.77       [thread 4][gcc -pthread] core/mount.o
#8 39.77       [thread 1][gcc -pthread] core/metrics.o
#8 39.77       [thread 6][gcc -pthread] core/plugins_builder.o
#8 39.77       [thread 2][gcc -pthread] core/sharedarea.o
#8 39.77       [thread 5][gcc -pthread] core/rpc.o
#8 39.77       [thread 0][gcc -pthread] core/gateway.o
#8 39.77       [thread 7][gcc -pthread] core/loop.o
#8 39.77       [thread 4][gcc -pthread] core/cookie.o
#8 39.77       [thread 6][gcc -pthread] core/querystring.o
#8 39.77       [thread 0][gcc -pthread] core/rb_timers.o
#8 39.77       [thread 5][gcc -pthread] core/transformations.o
#8 39.77       [thread 7][gcc -pthread] core/uwsgi.o
#8 39.77       [thread 3][gcc -pthread] proto/base.o
#8 39.77       [thread 2][gcc -pthread] proto/uwsgi.o
#8 39.77       [thread 6][gcc -pthread] proto/http.o
#8 39.77       [thread 4][gcc -pthread] proto/fastcgi.o
#8 39.77       [thread 5][gcc -pthread] proto/scgi.o
#8 39.77       [thread 0][gcc -pthread] proto/puwsgi.o
#8 39.77       [thread 2][gcc -pthread] lib/linux_ns.o
#8 39.77       [end of output]
#8 39.77
#8 39.77   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 39.78 error: legacy-install-failure
#8 39.78
#8 39.78 × Encountered error while trying to install package.
#8 39.78 ╰─> uwsgi
#8 39.78
#8 39.78 note: This is an issue with the package mentioned above, not pip.
#8 39.78 hint: See above for output from the failure.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -ex     && BUILD_DEPS="         build-essential         git         libexpat1-dev         libjpeg62-turbo-dev         libpcre3-dev         libpq-dev         zlib1g-dev     "     && apt-get update && apt-get install -y --no-install-recommends $BUILD_DEPS     && python3.10 -m venv /venv     && /venv/bin/pip install -U pip     && /venv/bin/pip install --no-cache-dir -r /requirements/production.txt     && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $BUILD_DEPS     && rm -rf /var/lib/apt/lists/*]: exit code: 1
```

**Comment by Pomax** [comment]
Using python 3.9, with redis 6.2, seems to make things work. With the updated PR I can now run the same set of commands as noted in the README.md section for docker, and end up with a working bakery site:

image

**Comment by Pomax** [comment]
@gasman with fewer changes than your branch needs, would this be worth landing?

**Comment by gasman** [comment]
When building from this branch (and waiting ~3 minutes after the `--build` step to avoid SQL issues caused by the database not being fully migrated yet) the `load_initial_data` step fails for me with an Elasticsearch "Connection refused" error. If I ignore that and continue with `docker-compose up`, I get a running Bakerydemo site but with broken search.

Testing against [the last revision before the 2.16 upgrade](https://github.com/wagtail/bakerydemo/commit/7b7d2891764387242293d6f405518779d05eb44c) shows that Elasticsearch has been broken all along - it's just that the addition of update_index to the load_initial_data task (for the benefit of the non-Docker setups that use the new database backend) has made this breakage visible during setup as well as when actually running a search.

Still, as this is a step up from the site not building at all, I'll go ahead and merge :-)

**Comment by Pomax** [comment]
oh wow, good discovery =S

**Comment by Amondale** [comment]
I would propose the following changes to readme.md (all docker 3.9-slim builds worked fine for me if I run migrate before loaddata -- not sure why?)


### Installation

Run the following commands:

```bash
git clone https://github.com/wagtail/bakerydemo.git
cd bakerydemo
docker-compose up --build -d
docker-compose run app /venv/bin/python manage.py migrate
docker-compose run app /venv/bin/python manage.py load_initial_data
docker-compose up

```

**Comment by Pomax** [comment]
Since this is the demo project, it would probably make even more sense to fold `python manage.py migrate` and `python manage.py load_initial_data` into the Dockerfile build steps. People shouldn't have to run those manually, that's just part of the initial bootstrap.

**Comment by Amondale** [comment]
That does make sense. However, somebody posted about a 3-minute delay while `python manage.py migrate` ran in the background, so if they are folded into the setup script (for some reason the docker-entrypoint.sh migrate if .. fi segment doesn't seem to always activate. I would vote too for `makemigrations` being part of the docker prep script to allow for customization of the demo env. It does no harm if there are no migrations needed, and if there are, they can cause errors in the `migrate` session. Your thoughts?

**Pull request merged**
